# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 17, 18, 52, 32, 546678, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 17, 18, 52, 32, 547190, tzinfo=utc), verbose_name='date created'),
        ),
    ]
