# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='related_partners',
            field=models.ManyToManyField(to='app.Partner'),
        ),
    ]
